from tkinter import *

root = Tk()

lb1 = Label(root, text='Dados Pessoais', font='Arial 26')
lb2 = Label(root, text='Nome:', font='Arial 26', anchor=E)
lb3 = Label(root, text='Nasc:', font='Arial 26', anchor=E)
lb4 = Label(root, text='CPF:', font='Arial 26', anchor=S)
lb5 = Label(root, text='Telefone:', font='Arial 26')
lb6 = Label(root, text='Endereço', font='Arial 26')
lb7 = Label(root, text='Rua:', font='Arial 26')
lb8 = Label(root, text='Bairro:', font='Arial 26')
lb9 = Label(root, text='CEP:', font='Arial 26')
lb10 = Label(root, text='Nº:', font='Arial 26')
lb11 = Label(root, text='UF:', font='Arial 26')
bt1 = Button(root, text='Gravar Dados', font='Arial 26')
bt2 = Button(root, text='Listar Dados', font='Arial 26')

en1 = Entry(root, font=lb2, width=30)
en2 = Entry(root, font=lb3, width=30)
en3 = Entry(root, font=lb4, width=30)

lb1.grid(row=0, column=0, sticky=NSEW)
lb2.grid(row=1, column=0)
en1.grid(row=1, column=1)
lb3.grid(row=2, column=0)
en2.grid(row=2, column=0)
lb4.grid(row=3, column=0)
en2.grid(row=3, column=1)
lb5.grid(row=4, column=0, sticky=NSEW)
lb6.grid(row=5, column=0, sticky=NSEW)
lb7.grid(row=6, column=0, sticky=NSEW)
lb8.grid(row=7, column=0, sticky=NSEW)
lb9.grid(row=8, column=0, sticky=NSEW)
lb10.grid(row=9, column=0, sticky=NSEW)
lb11.grid(row=10, column=0, sticky=NSEW)
bt1.grid(row=11, column=0, sticky=NSEW)
bt2.grid(row=11, column=1, sticky=NSEW)

root.mainloop()